HW 1
================
IRENE MARTINEZ MORATA (UNI: im2557)
9/27/2021

Set up: Load Libraries

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

``` r
set.seed(123)

data1 = tibble(
  set = rnorm(10, sd = .5), 
  nzero = (set > 0 ),
  character = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  levels = factor(c("green", "green", "green", "blue", "blue", "blue", "red", "red", "red", "red")))

print(data1)
```

    ## # A tibble: 10 × 4
    ##        set nzero character levels
    ##      <dbl> <lgl> <chr>     <fct> 
    ##  1 -0.280  FALSE a         green 
    ##  2 -0.115  FALSE b         green 
    ##  3  0.779  TRUE  c         green 
    ##  4  0.0353 TRUE  d         blue  
    ##  5  0.0646 TRUE  e         blue  
    ##  6  0.858  TRUE  f         blue  
    ##  7  0.230  TRUE  g         red   
    ##  8 -0.633  FALSE h         red   
    ##  9 -0.343  FALSE i         red   
    ## 10 -0.223  FALSE j         red

``` r
mean(pull(data1,set))
mean(pull(data1, as.numeric(nzero)))
mean(pull(data1, as.numeric(character)))
mean(pull(data1, as.numeric(levels)))
```

The mean of the sample from the standard Normal distribution (set) is
0.0373 The mean of the elements greater than 0 (nzero) is 0.5 The mean
of the character and factor vector cannot be determined because these
are non numerical variables, and cannot be successfully converted to
numerical.

## Problem 2

``` r
data("penguins", package = "palmerpenguins")
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts                 |
|:---------------|-----------:|---------------:|:--------|----------:|:----------------------------|
| species        |          0 |           1.00 | FALSE   |         3 | Ade: 152, Gen: 124, Chi: 68 |
| island         |          0 |           1.00 | FALSE   |         3 | Bis: 168, Dre: 124, Tor: 52 |
| sex            |         11 |           0.97 | FALSE   |         2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim\_variable      | n\_missing | complete\_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:--------------------|-----------:|---------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill\_length\_mm    |          2 |           0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill\_depth\_mm     |          2 |           0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper\_length\_mm |          2 |           0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body\_mass\_g       |          2 |           0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year                |          0 |           1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

``` r
plot1 <- ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()

ggsave("plot1.png")
```

    ## Saving 7 x 5 in image

``` r
print(plot1)
```

![](HW_1-im2557_files/figure-gfm/problem%202.1-1.png)<!-- -->

## Problem 2 elaboration

The penguins dataset is composed of 344 observations across 8 different
variables. There are 3 categorical variables: species, island and sex;
and 5 numeric variables: bill\_lenght\_mm, bill\_depth\_mm,
flipper\_length\_mm, body\_mass\_g, and year. The observations
colleceted data on 3 different categories of species (Ade, Gen, Chi),
and 3 different islands (Bis, Dre, Tor). 168 penguins were male and 165
were females. The mean flipper length is 201 millimeters, the mean body
mass was 4202 grams, the mean bill lenght and depth were 43.9 and 17.2
millimiters respectively. 11 observations are missing information on
sex, and 2 observations are missing information on all numeric variables
except from year.
